Repository HIGHFIVE-SW/post-service, pull requests merged in 2025-06, with the labels that each got.

#28 feat: exp scheduler 기능 구현
  src/main/java/com/trendist/post_service/PostServiceApplication.java
  src/main/java/com/trendist/post_service/domain/comment/service/CommentService.java
  src/main/java/com/trendist/post_service/domain/review/domain/Review.java
  src/main/java/com/trendist/post_service/domain/review/repository/ReviewRepository.java
  src/main/java/com/trendist/post_service/domain/review/service/ExpScheduler.java
  src/main/java/com/trendist/post_service/global/feign/user/client/UserServiceClient.java
  src/main/java/com/trendist/post_service/global/feign/user/dto/response/UserProfileResponse.java
  src/main/java/com/trendist/post_service/global/feign/user/dto/response/UserUpdateExpResponse.java
Labels: feat

#32 chore: ci/cd 구축
  .github/workflows/cd-prod.yaml
  .github/workflows/ci.yaml
Labels: chore

#36 refactor: ReviewGetResponse ocrResult 추가
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetResponse.java
Labels: refactor

#38 feat: 사용자의 월별 활동 개수 조회 기능 구현
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewProfileController.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewMonthlyCountResponse.java
  src/main/java/com/trendist/post_service/domain/review/repository/ReviewRepository.java
  src/main/java/com/trendist/post_service/domain/review/service/ExpScheduler.java
  src/main/java/com/trendist/post_service/domain/review/service/ReviewProfileService.java
Labels: feat

#40 refactor: imgOcrResult null값 처리 가능하게 수정
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewProfileController.java
  src/main/java/com/trendist/post_service/domain/review/domain/Review.java
  src/main/java/com/trendist/post_service/domain/review/service/ExpScheduler.java
Labels: refactor
