Repository HIGHFIVE-SW/post-service, pull requests merged in 2025-05, with the labels that each got.

#4 feat: Swagger 설정
  build.gradle
  src/main/java/com/trendist/post_service/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: chore, feat

#6 feat: openfeign을 통한 서비스 통신 및 s3 버킷에 이미지를 업로드 후 자유 게시판 게시물 생성 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/trendist/post_service/PostServiceApplication.java
  src/main/java/com/trendist/post_service/global/config/feign/FeignAuthConfig.java
  src/main/java/com/trendist/post_service/global/config/s3/S3Config.java
  src/main/java/com/trendist/post_service/global/feign/user/client/UserServiceClient.java
  src/main/java/com/trendist/post_service/global/feign/user/dto/UserProfileResponse.java
  src/main/java/com/trendist/post_service/global/response/status/ErrorStatus.java
  src/main/java/com/trendist/post_service/post/controller/PostController.java
  src/main/java/com/trendist/post_service/post/domain/Keyword.java
  src/main/java/com/trendist/post_service/post/domain/Post.java
  src/main/java/com/trendist/post_service/post/dto/request/PostCreateRequest.java
  src/main/java/com/trendist/post_service/post/dto/response/PostCreateResponse.java
  src/main/java/com/trendist/post_service/post/repository/PostRepository.java
  src/main/java/com/trendist/post_service/post/service/PostService.java
  src/main/java/com/trendist/post_service/s3/controller/PresignedUrlController.java
  src/main/java/com/trendist/post_service/s3/dto/request/PresignedUrlRequest.java
  src/main/java/com/trendist/post_service/s3/dto/response/PresignedUrlResponse.java
  src/main/java/com/trendist/post_service/s3/service/PresignedUrlService.java
  src/main/resources/application.yml
Labels: chore, feat

#8 feat: 자유 게시판 게시물 관련 api 구현
  src/main/java/com/trendist/post_service/domain/post/controller/PostController.java
  src/main/java/com/trendist/post_service/domain/post/domain/Keyword.java
  src/main/java/com/trendist/post_service/domain/post/domain/Post.java
  src/main/java/com/trendist/post_service/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/trendist/post_service/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostCreateResponse.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostDeleteResponse.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostGetAllResponse.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostGetMineResponse.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostGetResponse.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostUpdateResponse.java
  src/main/java/com/trendist/post_service/domain/post/repository/PostRepository.java
  src/main/java/com/trendist/post_service/domain/post/service/PostService.java
  src/main/java/com/trendist/post_service/domain/s3/controller/PresignedUrlController.java
  src/main/java/com/trendist/post_service/domain/s3/dto/request/PresignedUrlRequest.java
  src/main/java/com/trendist/post_service/domain/s3/dto/response/PresignedUrlResponse.java
  src/main/java/com/trendist/post_service/domain/s3/service/PresignedUrlService.java
  src/main/java/com/trendist/post_service/global/feign/user/client/UserServiceClient.java
  src/main/java/com/trendist/post_service/global/feign/user/dto/UserProfileResponse.java
  src/main/java/com/trendist/post_service/global/response/status/ErrorStatus.java
  src/main/java/com/trendist/post_service/post/controller/PostController.java
  src/main/java/com/trendist/post_service/post/repository/PostRepository.java
  src/main/java/com/trendist/post_service/post/service/PostService.java
Labels: feat

#11 feat: review 게시글 api 구현
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewController.java
  src/main/java/com/trendist/post_service/domain/review/domain/ActivityPeriod.java
  src/main/java/com/trendist/post_service/domain/review/domain/ActivityType.java
  src/main/java/com/trendist/post_service/domain/review/domain/Keyword.java
  src/main/java/com/trendist/post_service/domain/review/domain/Review.java
  src/main/java/com/trendist/post_service/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/trendist/post_service/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetAllResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetMineResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewUpdateResponse.java
  src/main/java/com/trendist/post_service/domain/review/repository/ReviewRepository.java
  src/main/java/com/trendist/post_service/domain/review/service/ReviewService.java
  src/main/java/com/trendist/post_service/global/response/status/ErrorStatus.java
Labels: feat, refactor

#14 feat: 리뷰 관련 조회 기능 구현 및 수상 기록 관련 필드 추가
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostGetAllResponse.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostGetResponse.java
  src/main/java/com/trendist/post_service/domain/post/service/PostService.java
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewController.java
  src/main/java/com/trendist/post_service/domain/review/domain/Review.java
  src/main/java/com/trendist/post_service/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/trendist/post_service/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetAllResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetKeywordCountResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetTypeCountResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewUpdateResponse.java
  src/main/java/com/trendist/post_service/domain/review/repository/ReviewRepository.java
  src/main/java/com/trendist/post_service/domain/review/service/ReviewService.java
  src/main/java/com/trendist/post_service/global/response/status/ErrorStatus.java
Labels: feat, refactor

#16 refactor: 리뷰 전체 조회, 정렬 기능 하나로 통합 구현
  src/main/java/com/trendist/post_service/domain/post/controller/PostController.java
  src/main/java/com/trendist/post_service/domain/post/controller/PostProfileController.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostGetUserResponse.java
  src/main/java/com/trendist/post_service/domain/post/service/PostProfileService.java
  src/main/java/com/trendist/post_service/domain/post/service/PostService.java
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewController.java
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewProfileController.java
  src/main/java/com/trendist/post_service/domain/review/domain/ReviewSort.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewGetUserResponse.java
  src/main/java/com/trendist/post_service/domain/review/repository/ReviewRepository.java
  src/main/java/com/trendist/post_service/domain/review/service/ReviewProfileService.java
  src/main/java/com/trendist/post_service/domain/review/service/ReviewService.java
Labels: feat, refactor

#18 feat: cdc 아키텍쳐를 통한 검색 기능 구현
  build.gradle
  src/main/java/com/trendist/post_service/domain/post/controller/PostController.java
  src/main/java/com/trendist/post_service/domain/post/controller/PostProfileController.java
  src/main/java/com/trendist/post_service/domain/post/domain/PostDocument.java
  src/main/java/com/trendist/post_service/domain/post/dto/response/PostSearchResponse.java
  src/main/java/com/trendist/post_service/domain/post/service/PostService.java
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewController.java
  src/main/java/com/trendist/post_service/domain/review/controller/ReviewProfileController.java
  src/main/java/com/trendist/post_service/domain/review/domain/Review.java
  src/main/java/com/trendist/post_service/domain/review/domain/ReviewDocument.java
  src/main/java/com/trendist/post_service/domain/review/domain/ReviewImageDocument.java
  src/main/java/com/trendist/post_service/domain/review/dto/request/ReviewActivityCreateRequest.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/trendist/post_service/domain/review/dto/response/ReviewSearchResponse.java
  src/main/java/com/trendist/post_service/domain/review/service/ReviewService.java
  src/main/java/com/trendist/post_service/domain/s3/controller/PresignedUrlController.java
  src/main/java/com/trendist/post_service/domain/s3/dto/request/PresignedUrlRequest.java
  src/main/java/com/trendist/post_service/domain/s3/dto/request/PresignedUrlsRequest.java
  src/main/java/com/trendist/post_service/domain/s3/dto/response/PresignedUrlResponse.java
  src/main/java/com/trendist/post_service/domain/s3/dto/response/PresignedUrlsResponse.java
  src/main/java/com/trendist/post_service/domain/s3/service/PresignedUrlService.java
  src/main/java/com/trendist/post_service/global/feign/activity/client/ActivityServiceClient.java
  src/main/java/com/trendist/post_service/global/feign/activity/dto/ActivityGetResponse.java
  src/main/resources/application.yml
Labels: chore, feat, refactor

#20 bug: prefix 오류 해결
  src/main/java/com/trendist/post_service/domain/s3/service/PresignedUrlService.java
Labels: bug
